---
- name: Configure docker on rhel8
  hosts: all
  vars:
    expose_port: 8080
    web_dir: "/myweb"

  tasks:
    - block:
        - name: yum repo for docker
          yum_repository:
            name: docker
            description: "Repo for Docker"
            file: docker_repo
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
            enabled: yes
            state: present
            gpgcheck: no

        - name: install docker package
          command: yum install -y docker-ce --nobest
          when: ansible_distribution ==  "RedHat"
          register: output

        - name: start and enable docker service
          service:
            name: docker
            state: started
            enabled: yes

        - name: firewall conf for docker
          firewalld:
            masquerade: yes
            state: enabled
            permanent: yes
            zone: public

        - name: enable firewall for docker port
          firewalld:
            port: "{{ item }}"
            zone: public
            permanent: yes
            state: enabled
            immediate: yes
          loop:
             - "80/tcp"
             - "443/tcp"
             - "{{ expose_port }}/tcp"
        
        - name: reload firewall
          service:
            name: firewalld
            state: reloaded

        - name: restart docker service
          service:
            name: docker
            state: restarted

        - name: install docker-py library
          pip:
            name: docker-py

        - name: pull httpd image
          docker_image:
            name: httpd
            source: pull

        - name: create myweb dir
          file:
            state: directory
            path: "{{ web_dir }}"
            mode: 0777

        - name: copy html webpage
          template:
            src: index.html.j2
            dest: "{{ web_dir }}/index.html"
        
        - name: run a container
          docker_container:
            name: mywebserverhttpd
            image: httpd
            state: started
            restart: yes
            ports:
              - "{{ expose_port }}:80"
            volumes:
              - "{{ web_dir }}:/usr/local/apache2/htdocs/"
         
        - name: debug ip:port
          debug: 
            msg: "Check you webserver on: http://{{ ansible_facts['default_ipv4']['address'] }}:{{ expose_port }}" 

      rescue:
        - debug:
            msg: "Failed with {{ output }}"

