---
# tasks file for webserver
- name: install httpd
  package:
    name: httpd
    state: present
 
- name: install php
  package:
    name: php
    state: present

- name: copy content
  template:
    src: index.php.j2
    dest: /var/www/html/index.php

- name: start webserver
  service:
    name: httpd
    state: started
    enabled: yes

