---
- name: play for downloading hadoop and java packages
  hosts: localhost
  become: false
  vars:
     - hadoop_pkg_url: "http://52.66.234.243/pub/hadoop-1.2.1-1.x86_64.rpm"
     - java_pkg_url: "http://52.66.234.243/pub/jdk-8u171-linux-x64.rpm"

  tasks:
    - name: download java rpm
      get_url:
        url: "{{ java_pkg_url }}"
        dest: "/tmp/java-jdk.rpm"

    - name: download hadoop rpm
      get_url:
        url: "{{ hadoop_pkg_url }}"
        dest: "/tmp/hadoop-1.2.1.rpm"
  
- name: hadoop configuration  
  hosts: all
  tasks:
    - block:
      - name: Copy java and hadoop rpm
        copy: 
          src: "{{ item }}"
          dest: "{{ item }}"
        loop: 
          - "/tmp/java-jdk.rpm"
          - "/tmp/hadoop-1.2.1.rpm"
      
      - name: install java rpm
        yum:
          name: "/tmp/java-jdk.rpm"
          state: present
          disable_gpg_check: yes

      - name: Install hadoop rpm
        command: "rpm -ivh /tmp/hadoop-1.2.1.rpm --force"
        when: ansible_distribution ==  "RedHat"
     
      - name: Stop and disable firewalld.
        service:
          name: firewalld
          state: stopped
          enabled: no
      
      - name: create directory for name node
        file:
          state: directory
          path: /nn
        when: inventory_hostname in groups['master']
      
      - name: copy hdfs-site.xml to nn
        copy:
          src: hdfs-site-nn.xml
          dest: /etc/hadoop/hdfs-site.xml
        when: inventory_hostname in groups['master']
        
      - name: copy core-site.xml to nn
        copy:
          src: core-site-nn.xml
          dest: /etc/hadoop/core-site.xml
        when: inventory_hostname in groups['master']
 
      - name: copy hdfs-site.xml to dn
        copy:
          src: hdfs-site-dn.xml
          dest: /etc/hadoop/hdfs-site.xml
        when: inventory_hostname in groups['slave']
        
      - name: copy core-site.xml to dn
        template:
          src: core-site-dn.xml
          dest: /etc/hadoop/core-site.xml
        when: inventory_hostname in groups['slave']
        
      - name: format namenode
        command: hadoop namenode -format -force
        when: inventory_hostname in groups['master']
        ignore_errors: yes

      - name: start namenode
        command: hadoop-daemon.sh start namenode
        when: inventory_hostname in groups['master']
        ignore_errors: yes

      - name: start datanode
        command: hadoop-daemon.sh start datanode
        when: inventory_hostname in groups['slave']
        ignore_errors: yes

      rescue:
        - name: debug the output
          debug:
            msg: "Playbook failed"
      
